on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3

    - name: ðŸ“‚ Sync to neyrinckaudio/docs-neyrinck
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DIST_REPO_PAT }}
      with:
        source-directory: 'site'
        destination-github-username: 'neyrinckaudio'
        destination-repository-name: 'docs-neyrinck'
        target-directory: 'v-control-pro'
        user-email: github-actions[bot]@users.noreply.github.com
        target-branch: main
        commit-message: 'Auto-deploy V-Control Pro site from ${{ github.repository }}'
